name: drone_configuration
kind: secret

pipeline:
  check for errors:
    name: check for errors
      image: node:6.3.0
      commands:
        - npm i
        - npm run build


  build an image:
    name: docker
    image: plugins/docker
      environment:
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
      tags:
        - latest
      dockerfile: ./Dockerfile
      commands:
        - docker login -u $username -p $password
        - docker build . -t ${username}i/supabase-app:${DRONE_COMMIT:0:7}
