name: drone_configuration
kind: secret

steps:
  check for errors:
    name: check for errors
      image: node:6.3.0
      commands:
        - npm i
        - npm run build


  build an image:
    name: d—âcker
    image: plugins/docker
      environment:
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
      tags:
        - latest
      dockerfile: ./Dockerfile
      commands:
        - docker login -u $DOCKER_USERNAME -p $REGISTRY_PASSWORD
        - docker build . -t ${DOCKER_USERNAME}i/supabase-app:${DRONE_COMMIT:0:7}
