name: drone_configuration
kind: secret
pipeline:
  run-tests:
    image: node:6.3.0
    commands:
      - cd ./api && npm i --quiet
      - npm test

  publish-api-docker:
    environment:
      DOCKER_USERNAME = monyshchuk
      DOCKER_EMAIL = mykolaon1@gmail.com
    image: plugins/docker:1.12
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: monyshchuk/supabase-app
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: ./