name: "Drone configuration"
kind: secret
type: docker
pipeline:
  - check for errors:
    name: "Check for errors"
    image: node
    commands:
      - npm install
      - npm run build
  - deploying image:
    name: "Docker"
    image: plugins/docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u $username -p $password
      - docker build . -t ${username}/supabase-app:${DRONE_COMMIT:0:7}
      - docker push ${username}/supabase-app