name: "Drone configuration"
kind: "secret"

pipeline:
  - check for errors:
      name: "Check for errors"
      image: $username/supabase-app
      commands:
        - npm i
        - npm run build


  - build an image:
      name: "Docker"
      image: plugins/docker
      environment:
        username:
          from_secret: DOCKER_USERNAME
        password:
          from_secret: DOCKER_PASSWORD
      tags:
        - latest
      dockerfile: ./Dockerfile
    commands:
      - docker login -u $username -p $password
      - docker build . -t ${username}i/supabase-app:${DRONE_COMMIT:0:7}