name: "Drone configuration"
kind: pipeline
type: docker
steps:
  - name: "Check for errors"
    image: node
    commands:
      - npm install
      - npm run build
  - name: "Docker"
    image: plugins/docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      DRONE_AGENTS_ENABLED=true
    commands:
      - docker login -u $username -p $password
      - docker build . -t monyshchuk/supabase-app
      - docker push monyshchuk/supabase-app